services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_LISTENERS: CONTROLLER://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "test-cluster"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: "kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    ports:
      - "9092:9092"
      - "9093:9093"

  yugabytedb:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb
    command: [ "bin/yugabyted", "start", "--daemon=false" ]
    ports:
      - "5433:5433"
      - "7001:7000"
    environment:
      YB_MASTER_ADDRESSES: "yugabytedb:7100"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://yugabytedb:7000" ]
      interval: 30s
      timeout: 10s
      retries: 5

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5678:5678"
    depends_on:
      - kafka
      - yugabytedb
    volumes:
      - ./test_target.txt:/app/test_target.txt