services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_LISTENERS: CONTROLLER://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "test-cluster"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: "kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9093:9093"

  yugabytedb:
    build:
      context: .
      dockerfile: Dockerfile.yugabyte
    container_name: yugabytedb
    entrypoint: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/startup.sh"]
    ports:
      - "5433:5433"
      - "7001:7000"
    environment:
      YB_MASTER_ADDRESSES: "yugabytedb:7100"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://yugabytedb:7000" ]
      interval: 30s
      timeout: 10s
      retries: 5

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5678:5678"
    depends_on:
      - kafka
      - yugabytedb
      - kafka_connect
    volumes:
      - ./test_target.txt:/app/test_target.txt

  kafka_connect:
    build:
      context: .
      dockerfile: Dockerfile.kafka_connect
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka_connect
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-statuses"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka_connect
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: "/plugins"
      CONNECT_BIGQUERY_PROJECT: "your-gcp-project-id"
      CONNECT_BIGQUERY_KEYFILE: "/path/to/your/keyfile.json"
      CONNECT_BIGQUERY_SINK_TASKS_MAX: "1"
      CONNECT_BIGQUERY_SINK_TOPICS: "your-topic-name"
      CONNECT_BIGQUERY_SINK_SCHEMA_RETRIEVAL_MODE: "AUTO"
      CONNECT_BIGQUERY_SINK_TABLE_CREATE: "true"
      CONNECT_BIGQUERY_SINK_TABLE_CREATE_IF_NOT_EXISTS: "true"
      CONNECT_BIGQUERY_SINK_TABLE_CREATE_PARTITIONED: "true"
      CONNECT_BIGQUERY_SINK_TABLE_CREATE_CLUSTERED: "true"
      CONNECT_BIGQUERY_SINK_TABLE_CREATE_CLUSTERED_COLUMNS: "column1,column2"
    ports:
      - "8083:8083"